
package publicar.usuarioturisticasservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ContraseniaInvalidaException", targetNamespace = "http://usuarioTuristicasService.publicar/")
public class ContraseniaInvalidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ContraseniaInvalidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ContraseniaInvalidaException_Exception(String message, ContraseniaInvalidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ContraseniaInvalidaException_Exception(String message, ContraseniaInvalidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.usuarioturisticasservice.ContraseniaInvalidaException
     */
    public ContraseniaInvalidaException getFaultInfo() {
        return faultInfo;
    }

}
