
package publicar.actividadesturisticasservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "AltaInscripcionPosteriorAFechaSalidaException", targetNamespace = "http://actividadesturisticasservice.publicar/")
public class AltaInscripcionPosteriorAFechaSalidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AltaInscripcionPosteriorAFechaSalidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AltaInscripcionPosteriorAFechaSalidaException_Exception(String message, AltaInscripcionPosteriorAFechaSalidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public AltaInscripcionPosteriorAFechaSalidaException_Exception(String message, AltaInscripcionPosteriorAFechaSalidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.actividadesturisticasservice.AltaInscripcionPosteriorAFechaSalidaException
     */
    public AltaInscripcionPosteriorAFechaSalidaException getFaultInfo() {
        return faultInfo;
    }

}
