
package publicar.paqueteturisticasservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServicePaquetes", targetNamespace = "http://paqueteturisticasservice.publicar/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicePaquetes {


    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.paqueteturisticasservice.DtPaqueteDetalles
     * @throws ObjetoNoExisteEnTurismoUy_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDtPaqueteDetalleRequest", output = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDtPaqueteDetalleResponse", fault = {
        @FaultAction(className = ObjetoNoExisteEnTurismoUy_Exception.class, value = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDtPaqueteDetalle/Fault/ObjetoNoExisteEnTurismoUy")
    })
    public DtPaqueteDetalles obtenerDtPaqueteDetalle(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ObjetoNoExisteEnTurismoUy_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.paqueteturisticasservice.DtPaqueteCollection
     * @throws ObjetoNoExisteEnTurismoUy_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDTPaquetesPorCategoriaRequest", output = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDTPaquetesPorCategoriaResponse", fault = {
        @FaultAction(className = ObjetoNoExisteEnTurismoUy_Exception.class, value = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDTPaquetesPorCategoria/Fault/ObjetoNoExisteEnTurismoUy")
    })
    public DtPaqueteCollection obtenerDTPaquetesPorCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ObjetoNoExisteEnTurismoUy_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws CompraYaRegistradaException_Exception
     * @throws ObjetoNoExisteEnTurismoUy_Exception
     * @throws PaquetesSinActividadesExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://paqueteturisticasservice.publicar/WebServicePaquetes/comprarPaqueteRequest", output = "http://paqueteturisticasservice.publicar/WebServicePaquetes/comprarPaqueteResponse", fault = {
        @FaultAction(className = ObjetoNoExisteEnTurismoUy_Exception.class, value = "http://paqueteturisticasservice.publicar/WebServicePaquetes/comprarPaquete/Fault/ObjetoNoExisteEnTurismoUy"),
        @FaultAction(className = CompraYaRegistradaException_Exception.class, value = "http://paqueteturisticasservice.publicar/WebServicePaquetes/comprarPaquete/Fault/CompraYaRegistradaException"),
        @FaultAction(className = PaquetesSinActividadesExcepcion_Exception.class, value = "http://paqueteturisticasservice.publicar/WebServicePaquetes/comprarPaquete/Fault/PaquetesSinActividadesExcepcion")
    })
    public void comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws CompraYaRegistradaException_Exception, ObjetoNoExisteEnTurismoUy_Exception, PaquetesSinActividadesExcepcion_Exception
    ;

    /**
     * 
     * @return
     *     returns publicar.paqueteturisticasservice.DtPaqueteCollection
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDtPaquetesRequest", output = "http://paqueteturisticasservice.publicar/WebServicePaquetes/obtenerDtPaquetesResponse")
    public DtPaqueteCollection obtenerDtPaquetes();

}
