
package publicar.paqueteturisticasservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PaquetesSinActividadesExcepcion", targetNamespace = "http://paqueteTuristicasService.publicar/")
public class PaquetesSinActividadesExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PaquetesSinActividadesExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PaquetesSinActividadesExcepcion_Exception(String message, PaquetesSinActividadesExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PaquetesSinActividadesExcepcion_Exception(String message, PaquetesSinActividadesExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.paqueteturisticasservice.PaquetesSinActividadesExcepcion
     */
    public PaquetesSinActividadesExcepcion getFaultInfo() {
        return faultInfo;
    }

}
