
package publicar.paqueteturisticasservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServicePaquetes", targetNamespace = "http://paqueteTuristicasService.publicar/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicePaquetes {


    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.paqueteturisticasservice.DtPaqueteDetalles
     * @throws ObjetoNoExisteEnTurismoUy_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDtPaqueteDetalleRequest", output = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDtPaqueteDetalleResponse", fault = {
        @FaultAction(className = ObjetoNoExisteEnTurismoUy_Exception.class, value = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDtPaqueteDetalle/Fault/ObjetoNoExisteEnTurismoUy")
    })
    public DtPaqueteDetalles obtenerDtPaqueteDetalle(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ObjetoNoExisteEnTurismoUy_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.paqueteturisticasservice.DtPaqueteCollection
     * @throws ObjetoNoExisteEnTurismoUy_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDTPaquetesPorCategoriaRequest", output = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDTPaquetesPorCategoriaResponse", fault = {
        @FaultAction(className = ObjetoNoExisteEnTurismoUy_Exception.class, value = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDTPaquetesPorCategoria/Fault/ObjetoNoExisteEnTurismoUy")
    })
    public DtPaqueteCollection obtenerDTPaquetesPorCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ObjetoNoExisteEnTurismoUy_Exception
    ;

    /**
     * 
     * @return
     *     returns publicar.paqueteturisticasservice.DtPaqueteCollection
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDtPaquetesRequest", output = "http://paqueteTuristicasService.publicar/WebServicePaquetes/obtenerDtPaquetesResponse")
    public DtPaqueteCollection obtenerDtPaquetes();

}
