
package publicar.maestroservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServiceMaestro", targetNamespace = "http://maestroServices.publicar/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceMaestro {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws ObjetoNoExisteEnTurismoUy_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://maestroServices.publicar/WebServiceMaestro/getImgRequest", output = "http://maestroServices.publicar/WebServiceMaestro/getImgResponse", fault = {
        @FaultAction(className = ObjetoNoExisteEnTurismoUy_Exception.class, value = "http://maestroServices.publicar/WebServiceMaestro/getImg/Fault/ObjetoNoExisteEnTurismoUy")
    })
    public byte[] getImg(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ObjetoNoExisteEnTurismoUy_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @return
     *     returns publicar.maestroservices.DtResultadoBusqueda
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://maestroServices.publicar/WebServiceMaestro/buscarRequest", output = "http://maestroServices.publicar/WebServiceMaestro/buscarResponse")
    public DtResultadoBusqueda buscar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        TipoOrdenacion arg3);

}
