
package publicar.maestroservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import configuraciones.Cargador;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServiceMaestroService", targetNamespace = "http://maestroservices.publicar/", wsdlLocation = "CONFIO QUE NO IMPORTA")
public class WebServiceMaestroService
    extends Service
{

    private final static URL WEBSERVICEMAESTROSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEMAESTROSERVICE_EXCEPTION;
    private final static QName WEBSERVICEMAESTROSERVICE_QNAME = new QName("http://maestroservices.publicar/", "WebServiceMaestroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Cargador.getDirrecionDelCentral() + "/maestro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEMAESTROSERVICE_WSDL_LOCATION = url;
        WEBSERVICEMAESTROSERVICE_EXCEPTION = e;
    }

    public WebServiceMaestroService() {
        super(__getWsdlLocation(), WEBSERVICEMAESTROSERVICE_QNAME);
    }

    public WebServiceMaestroService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEMAESTROSERVICE_QNAME, features);
    }

    public WebServiceMaestroService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEMAESTROSERVICE_QNAME);
    }

    public WebServiceMaestroService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEMAESTROSERVICE_QNAME, features);
    }

    public WebServiceMaestroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceMaestroService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceMaestro
     */
    @WebEndpoint(name = "WebServiceMaestroPort")
    public WebServiceMaestro getWebServiceMaestroPort() {
        return super.getPort(new QName("http://maestroservices.publicar/", "WebServiceMaestroPort"), WebServiceMaestro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceMaestro
     */
    @WebEndpoint(name = "WebServiceMaestroPort")
    public WebServiceMaestro getWebServiceMaestroPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://maestroservices.publicar/", "WebServiceMaestroPort"), WebServiceMaestro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEMAESTROSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEMAESTROSERVICE_EXCEPTION;
        }
        return WEBSERVICEMAESTROSERVICE_WSDL_LOCATION;
    }

}
