
package publicar.actividadesturisticasservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ErrorAlProcesar", targetNamespace = "http://actividadesTuristicasService.publicar/")
public class ErrorAlProcesar_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorAlProcesar faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ErrorAlProcesar_Exception(String message, ErrorAlProcesar faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ErrorAlProcesar_Exception(String message, ErrorAlProcesar faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.actividadesturisticasservice.ErrorAlProcesar
     */
    public ErrorAlProcesar getFaultInfo() {
        return faultInfo;
    }

}
