
package publicar.actividadesturisticasservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PaqueteNoCompradoExcepcion", targetNamespace = "http://actividadesTuristicasService.publicar/")
public class PaqueteNoCompradoExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PaqueteNoCompradoExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PaqueteNoCompradoExcepcion_Exception(String message, PaqueteNoCompradoExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PaqueteNoCompradoExcepcion_Exception(String message, PaqueteNoCompradoExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.actividadesturisticasservice.PaqueteNoCompradoExcepcion
     */
    public PaqueteNoCompradoExcepcion getFaultInfo() {
        return faultInfo;
    }

}
